### ISSUE TITLE
test result very poor with the Trans10k test dataset

### ISSUE THREAD

**Issue by ynma-hanvo** [hehao13/EBLNet#8]
following your test instruction for testing a subset of the test dataset, but got very poor result as below,
02-17 10:15:55.625 label_id     label     iou    acc    Ber    Precision Recall TP    FP    FN
02-17 10:15:55.625  0       background    8.02597    0.08345    0.71509    0.08345    0.67763    5.88020  10.98382    0.03970
02-17 10:15:55.626  1           things    2.47790    0.02682    0.93973    0.02682    0.24570    0.18703  36.28676    0.08233
02-17 10:15:55.626  2            stuff    21.99346    0.90403    0.51912    0.90403    0.22519    20.39371  0.10616    3.11043
02-17 10:15:55.626 mean iou: 0.10832445945247353
02-17 10:15:55.626 macc: 0.33809681467115804
02-17 10:15:55.626 all acc: 0.26460952758789064
02-17 10:15:55.626 mae: 1.3971702575683593
02-17 10:15:55.626 mBer: 0.7246458341306413

and by the way, i got different values for mean iou at each run (all below <0.3)    ,
I am expecting to get at least 0.5   . 
what is wrong  ?

**Comment by ynma-hanvo** [comment]
c

**Comment by ynma-hanvo** [comment]
already fixed . thank you very much

**Comment by 07hokage** [comment]
@ynma-hanvo , how did you fix it? i'm still getting poor results. Would you please let me know what the fix was?
