### ISSUE TITLE
i have a problem with pytorch version

### ISSUE THREAD

**Issue by dongshenhan** [hehao13/EBLNet#9]
because of my gpu, i have to use cuda 11.3and pytorch 1.10,and i have a error  which is output 0 of ReluBackward0. 
the all of error is follow:
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [4, 96, 256]], which is output 0 of ReluBackward0, is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

so can you induct me that why the resnet backward is 0,    i find that  the problem musb be the code of main_loss.backward()~~~~~~
and the major problem is the difference with pytorch‘version   

thank you ~ thans

**Comment by wanyc-rt** [comment]
solve your problem, through updating your torch version to 1.7,or higher

**Comment by dongshenhan** [comment]
SORRY i forget to close my ques, the main reason is in the gsn.py,  which code have  z+=4,  it can make relu have a 0 backward ,i hope it can help solve any other people.  thanks
